version: '2.0'

services:
 tshark:
  container_name: tshark  
  build: ./
  restart: always 
  entrypoint:
    - tshark
    - -t
    - u
    - -Y
    - "gsmtap and not icmp"
 scat:
  container_name: scat  
  build: ./
  links:
    - tshark
  restart: always 
  devices:
   - /dev/bus/usb/003/050
  entrypoint:
   - python3
   - scat.py
   - -t
   - "sec"
   - -m
   - e333
   - -u
   - -a
   - 003:050
   - -i 
   - "2" 
   - -H  
   - tshark
